---
- name: set-cluster
  shell: >
    kubectl config set-cluster kubernetes-the-hard-way \
    --certificate-authority=ca.pem \
    --embed-certs=true \
    --server=https://127.0.0.1:6443 \
    --kubeconfig=admin.kubeconfig
  args:
    chdir: "{{ k8s_conf_files_dir }}"
    #creates: "{{ k8s_conf_files_dir }}/admin.kubeconfig"

- name: set-credentials
  shell: >
    kubectl config set-credentials admin \
    --client-certificate=admin.pem \
    --client-key=admin-key.pem \
    --embed-certs=true \
    --kubeconfig=admin.kubeconfig
  args:
    chdir: "{{ k8s_conf_files_dir }}"
    #creates: "{{ k8s_conf_files_dir }}/admin.kubeconfig"

- name: set-context
  shell: >
    kubectl config set-context default \
    --cluster=kubernetes-the-hard-way \
    --user=admin \
    --kubeconfig=admin.kubeconfig
  args:
    chdir: "{{ k8s_conf_files_dir }}"
    #creates: "{{ k8s_conf_files_dir }}/admin.kubeconfig"

- name: use-context
  shell:
  args:
    chdir: "{{ k8s_conf_files_dir }}"
    cmd: kubectl config use-context default --kubeconfig=admin.kubeconfig
