---
- name: Download kubectl binary (OSX amd64)
  get_url:
    url: "{{ kubectl_dl_url }}"
    dest: "/usr/local/bin/kubectl"
  mode: 0755
  owner: "{{ user_id }}"
  group: "{{ user_id }}"

- name: Autocompletion for zsh
  lineinfile:
    path: /Users/{{ user_id }}/.zshrc
    line: source <(kubectl completion zsh)
    insertbefore: BOF
  when: {{ shell_type }} == 'zsh'