---
- name: Download cni plugins
  get_url:
    url: "{{ archives.cni_plugins.url }}"
    dest: "/tmp/{{ archives.cni_plugins.file }}"
  notify:  Extract cni plugins

#- name: Delete cni plugins archive
#  file:
#    path: "/tmp/{{ archives.cni_plugins.file }}"
#    state: absent

- name: Create CNI bridge conf
  template:
    src: 10-bridge.conf.j2
    dest: /etc/cni/net.d/10-bridge.conf

- name: Create CNI loopback conf
  template:
    src: 99-loopback.conf.j2
    dest: /etc/cni/net.d/99-loopback.conf
