---
- name: Download cni plugins
  get_url:
    url: "{{ archives.cni_plugins.url }}"
    dest: "/tmp/{{ archives.cni_plugins.file }}"
    
- name: Extract cni plugins
  unarchive:
    src: "/tmp/{{ archives.cni_plugins.file }}"
    remote_src: yes
    dest: /opt/cni/bin
    extra_opts: [--strip-components=1]

- name: Delete cni plugins archive
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/tmp/{{ archives.cni_plugins.file }}"

- name: Create CNI bridge conf
  template:
    src: 10-bridge.conf.j2
    dest: /etc/cni/net.d/10-bridge.conf

- name: Create CNI loopback conf
  template:
    src: 99-loopback.conf.j2
    dest: /etc/cni/net.d/99-loopback.conf
