---
- name: Download containerd
  get_url:
    url: "{{ archives.containerd.url }}"
    dest: "/tmp/{{ archives.containerd.file }}"

- name: Extract containerd
  unarchive:
    src: "/tmp/{{ archives.containerd.file }}"
    remote_src: yes
    dest: /tmp/containerd/
    extra_opts: [--strip-components=1]
    mode: 0700
    owner: root
    group: root

- name: Copy containerd binaries to /bin
  copy:
    src: /tmp/containerd/
    dest: /bin/
    remote_src: yes

- name: Delete containerd archive files
  ignore_errors: yes
  file:
    path: /tmp/containerd
    state: absent
    recurse: yes

- name: Create containerd config
  copy:
    src: containerd_config.toml
    dest: /etc/containerd/config.toml

- name: Create containerd unit file
  copy:
    src: containerd.service
    dest: /etc/systemd/system/containerd.service
  notify: Reload systemd units

- name: Enable and start containerd service
  systemd:
    name: containerd
    enabled: yes
    state: started