---
- name: Download kube node binaries
  get_url:
    url: "{{ item.url }}"
    dest: "/usr/local/bin/{{ item.dest }}"
  loop: "{{ downloads }}"

- name: Download cri tools
  get_url:
    url: "{{ archives.cri_tools.url }}"
    dest: "/tmp/{{ archives.cri_tools.file }}"
    
- name: Extract cri tools
  unarchive:
    src: "/tmp/{{ archives.cri_tools.file }}"
    remote_src: yes
    dest: /usr/local/bin
    extra_opts: [--strip-components=1]

- name: Delete cri tools archive
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/tmp/{{ archives.cri_tools.file }}"

- name: Download cni plugins
  get_url:
    url: "{{ archives.cni_plugins.url }}"
    dest: "/tmp/{{ archives.cni_plugins.file }}"
    
- name: Extract cni plugins
  unarchive:
    src: "/tmp/{{ archives.cni_plugins.file }}"
    remote_src: yes
    dest: /opt/cni/bin
    extra_opts: [--strip-components=1]

- name: Delete cni plugins archive
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/tmp/{{ archives.cni_plugins.file }}"

- name: Download containerd
  get_url:
    url: "{{ archives.containerd.url }}"
    dest: "/tmp/{{ archives.containerd.file }}"
    
- name: Extract containerd
  unarchive:
    src: "/tmp/{{ archives.containerd.file }}"
    remote_src: yes
    dest: /tmp/containerd/
    extra_opts: [--strip-components=1]

- name: Copy containerd binaries to /bin
  copy:
    src: /tmp/containerd/containerd/bin/
    dest: /bin/
    remote_src: yes
    mode: 0700
    owner: root
    group: root

- name: Delete containerd archive files
  file:
    path: /tmp/containerd
    state: absent
    recurse: yes