---
- name: Create kubelet config
  template:
    src: kubelet-config.yaml.j2
    dest: /var/lib/kubelet/kubelet-config.yaml

- name: Create kubelet unit file
  copy:
    src: kubelet.service
    dest: /etc/systemd/system/kubelet.service
  notify: Reload systemd units

- name: Enable and start kubelet service
  systemd:
    name: kubelet
    enabled: yes
    state: started