---
- name: Perform system conf tasks
  include_tasks: conf.yml

- name: Copy node certs
  copy:
    src: "{{ cert_dir }}/{{ item }}"
    dest: /home/vagrant
  loop: 
    - "{{ inventory_hostname_short }}-key.pem"
    - "{{ inventory_hostname_short }}.pem"
    - ca.pem

- name: Copy kube conf files
  copy:
    src: "{{ cert_dir }}/{{ item }}"
    dest: /home/vagrant
  loop: 
    - "{{ inventory_hostname_short }}.kubeconfig"
    - kube-proxy.kubeconfig

- name: Install kubectl
  include_role:
    name: githubixx.kubectl
  vars:
    kubectl_version: "{{ k8s_version }}"

- name: Download Kubernetes node bits
  include_tasks: downloads.yml

- name: Download and configure CNI plugins
  include_tasks: cni.yml

- name: Download and configure containerd
  include_tasks: containerd.yml
