---
- name: Install apt packages for k8s nodes
  apt:
    update_cache: yes
    name:
      - socat
      - conntrack
      - ipset

- name: Create k8s directories
  file:
    state: directory
    recurse: yes
    path: "{{ item }}"
  loop:
    - /etc/cni/net.d
    - /opt/cni/bin
    - /var/lib/kubelet
    - /var/lib/kube-proxy
    - /var/lib/kubernetes
    - /var/run/kubernetes

- name: Copy node certs
  copy:
    src: "{{ cert_dir }}/{{ item }}"
    dest: /home/vagrant
  loop: 
    - "{{ inventory_hostname_short }}-key.pem"
    - "{{ inventory_hostname_short }}.pem"
    - ca.pem

- name: Copy kube conf files
  copy:
    src: "{{ cert_dir }}/{{ item }}"
    dest: /home/vagrant
  loop: 
    - "{{ inventory_hostname_short }}.kubeconfig"
    - kube-proxy.kubeconfig

- name: Download Kubernetes node bits
  include_tasks: downloads.yml
