---
#
# Configure vbox host, generate tls certs, kubectl conf files
#
- hosts: localhost
  become: yes
  vars:
    docker_group_members:
      - "{{ local_id }}"
  tasks:
  - name: Configure host system components
    include_role:
      name: vbox-host

# install kubectl on all systems
- hosts:
  - k8s_controller
  - localhost
  become: yes
  tasks:
  - name: Install kubectl
    include_role:
      name: githubixx.kubectl
    vars:
      kubectl_version: "{{ k8s_version }}"

# Create etcd cluster
- hosts: k8s_etcd
  become: yes
  tasks:
  - name: Install and configure etcd
    include_role:
      name: k8s-etcd

# Setup k8s controllers
- hosts: k8s_controller
  become: yes
  tasks:
  - name: Install and configure controller services
    include_role:
      name: k8s-controller
  - name: Create .kube dir for root user
    copy:
      path: "/root/.kube"
      state: directory
  - name: Copy kubeconfig files
    copy:
      src: "{{ k8s_conf_files_dir }}/admin.kubeconfig"
      dest: "/root/.kube/config"

# configure rbac - runs once, from one controller -- should change this to run from the host system
- hosts: kc1
  become: yes

  tasks:
  - name: Copy RBAC config - ClusterRole
    copy:
      src: "./files/rbac_clusterrole.yml"
      dest: "/var/lib/kubernetes/rbac_clusterrole.yml"
      owner: root
      group: root
    notify: Apply yaml ClusterRole
  - name: Copy RBAC config - ClusterRoleBinding
    copy:
      src: "./files/rbac_clusterrole.yml"
      dest: "/var/lib/kubernetes/rbac_clusterrolebinding.yml"
      owner: root
      group: root
    notify: Apply yaml ClusterRoleBinding

  handlers:
  - name: Apply yaml ClusterRole
    shell:
      cmd: kubectl apply --kubeconfig /var/lib/kubernetes/admin.kubeconfig -f /var/lib/kubernetes/rbac_clusterrole.yml

  - name: Apply yaml ClusterRoleBinding
    shell:
      cmd: kubectl apply --kubeconfig /var/lib/kubernetes/admin.kubeconfig -f /var/lib/kubernetes/rbac_clusterrolebinding.yml

# Setup k8s nodes
- hosts: k8s_node
  become: yes
  tasks:
  - name: Install and configure node services
    include_role:
      name: k8s-node