---
- hosts: all
  become: yes
  tasks:
    - name: Install kubectl
      include_role:
        name: githubixx.kubectl
      vars:
        kubectl_version: "{{ k8s_version }}"

- hosts: localhost
  become: yes
  tasks:
  #- name: Generate hosts file
  #  lineinfile:
  #    path: /etc/hosts
  #    line: "{{ item. }} {{ item. }}"
  #  loop: {{ groups['k8s_controller'] | combine(groups['k8s_node'], recursive=True) }}

  - name: Generate an OpenSSH keypair with the default values (4096 bits, rsa)
    openssh_keypair:
      path: "/home/{{ local_id }}/.ssh/id_rsa_{{ user_id }}"
      owner: "{{ local_id }}"
      group: "{{ local_id }}"

  - name: Fix owner of the generated pub key
    file:
      path: "/home/{{ local_id }}/.ssh/id_rsa_{{ user_id }}"
      owner: "{{ local_id }}"
      group: "{{ local_id }}"

  - name: Install cfssl and generate k8s TLS certs
    include_role: k8s-ca

  - name: Generate encryption config
    import_tasks: ./tasks/encryption_key.yml
  
  - name: kubelet config
    include_tasks: ./tasks/conf_kubelet.yml

  - name: kube proxy config
    include_tasks: ./tasks/conf_kube-proxy.yml

  - name: controller-manager config
    include_tasks: ./tasks/conf_cont-mgr.yml

  - name: kube-scheduler config
    include_tasks: ./tasks/conf_kube-sched.yml

  - name: kube admin config
    include_tasks: ./tasks/conf_admin.yml

  - name: Fix owner of kube certs and conf files
    file:
      path: "{{ cert_dir }}"
      owner: "{{ local_id }}"
      group: "{{ local_id }}"
      mode: "0660"