---
#
# Configure vbox host, generate tls certs, kubectl conf files
#
- hosts: localhost
  become: yes
  tags: vbox_host_only
  vars:
    docker_group_members:
      - "{{ local_id }}"
  tasks:
  - name: Configure host system components
    include_role:
      name: vbox-host

  # - name: Get all k8s hosts
  #   set_fact:
  #     k8sHosts: "{{groups['k8s_controller'] + groups['k8s_node']}}"
  # - name: Get all k8s hosts for hosts file
  #   set_fact:
  #     hostsFileContent: >-
  #       {% set comma = joiner("\n") %}{% for item in k8sHosts -%}
  #         {{ hostvars[item]["ansible_"+hostvars[item]["private_if"]].ipv4.address }} {{ comma() }}
  #       {%- endfor %}


# install kubectl on all systems
- hosts:
  - k8s_controller
  - localhost
  become: yes
  tasks:
  - name: Install kubectl
    include_role:
      name: githubixx.kubectl
    vars:
      kubectl_version: "{{ k8s_version }}"

# Create etcd cluster
- hosts: k8s_etcd
  become: yes
  tags: etcd_only
  tasks:
  - name: Install and configure etcd
    include_role:
      name: k8s-etcd

# Setup k8s controllers
- hosts: k8s_controller
  become: yes
  tags: controller_only
  tasks:
    - name: Install and configure controller services
      include_role:
        name: k8s-controller
    - name: Create .kube dir for root user
      file:
        path: "/root/.kube"
        state: directory
    - name: Copy kubeconfig files
      copy:
        src: "{{ k8s_conf_files_dir }}/admin.kubeconfig"
        dest: "/root/.kube/config"

# configures controller ability to talk to work nodes
- hosts: localhost
  become: yes
  tags: run_once
  tasks:
    - name: Apply API to Nodes cluster role and cluster role binding
      shell:
        cmd: kubectl apply --kubeconfig "{{ k8s_conf_files_dir }}/admin.kubeconfig" -f "{{ playbook_dir }}/files/api-to-nodes-rbac.yaml"
    - name: Create coredns yaml
      template:
        src: "./files/coredns.yaml.j2"
        dest: "{{ k8s_conf_files_dir }}/coredns.yaml" #"/var/lib/kubernetes/coredns.yaml"
        owner: "{{ local_id }}"
        group: "{{ local_id }}"
    - name: Apply yaml coredns
      shell:
        cmd: kubectl apply --kubeconfig "{{ k8s_conf_files_dir }}/admin.kubeconfig" -f "{{ k8s_conf_files_dir }}/coredns.yaml"
    - name: Apply yaml Calico
      shell:
        cmd: kubectl apply --kubeconfig "{{ k8s_conf_files_dir }}/admin.kubeconfig" -f https://docs.projectcalico.org/manifests/calico.yaml

# Setup k8s nodes
- hosts: k8s_node
  become: yes
  tags: node_only
  tasks:
    - name: Install and configure node services
      include_role:
        name: k8s-node