---
- name: Install controller binaries
  get_url:
    url: "https://storage.googleapis.com/kubernetes-release/release/v{{ k8s_version }}/bin/linux/amd64/{{ item }}"
    dest: /usr/local/bin
    mode: "0750"
  loop: "{{ k8s_controller_bins }}"