---
- name: Create kube scheduler config file
  template:
    src: kube-scheduler.yml.j2
    dest: /etc/kubernetes/config/kube-scheduler.yml

- name: Configure RBAC files
  template:
    src: "./templates/{{item}}"
    dest: "/var/lib/kubernetes/{{item}}"
  loop:
  - rbac_clusterrole.yml
  - rbac_clusterrolebinding.yml
  notify: Apply yaml