---
- name: Create API server unit file
  template:
    src: ./templates/kube-apiserver.service.j2
    dest: /etc/systemd/system/kube-apiserver.service

- name: Create kube controller manager unit file
  template:
    src: ./templates/kube-controller-manager.service.j2
    dest: /etc/systemd/system/kube-controller-manager.service

- name: Create kube scheduler config file
  template:
    src: ./templates/kube-scheduler.yml.j2
    dest: /etc/kubernetes/config/kube-scheduler.yml

- name: Create kube scheduler unit file
  template:
    src: ./templates/kube-scheduler.service.j2
    dest: /etc/systemd/system/kube-scheduler.service

- name: Reload systemd units
  systemd:
    daemon_reload: yes

- name: Enable and start kube controller services
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
