---
versions:
  cni_plugins: "0.8.6"
  containerd: "1.3.6"
  cri_tools: "1.18.0"
  runc: "1.0.0-rc91"
  
downloads:
  - url: https://github.com/opencontainers/runc/releases/download/v{{ versions.runc }}/runc.amd64
    dest: runc
  - url: https://storage.googleapis.com/kubernetes-release/release/v{{ k8s_version }}/bin/linux/amd64/kube-proxy
    dest: kube-proxy
  - url: https://storage.googleapis.com/kubernetes-release/release/v{{ k8s_version }}/bin/linux/amd64/kubelet
    dest: kubelet

archvives:
  - https://github.com/kubernetes-sigs/cri-tools/releases/download/v{{ versions.cri_tools }}/crictl-v{{ versions.cri_tools }}-linux-amd64.tar.gz
  - https://github.com/containerd/containerd/releases/download/v{{ versions.containerd }}/containerd-{{ versions.containerd }}.linux-amd64.tar.gz
  - https://github.com/containernetworking/plugins/releases/download/v{{ versions.cni_plugins }}/cni-plugins-amd64-v{{ versions.cni_plugins }}.tgz
